from flask import g, request
from datetime import datetime
from flask_login import current_user
from SoftyTechCMS.logs.database_manager import save_request_log


def before_request():
    """
    Action to be taken before handling each incoming request.

    This function is executed before any view function is called for an incoming request.

    Returns:
        None
    """
    # Store the current timestamp in the "start_time" attribute of the Flask global object (g)
    g.start_time = datetime.utcnow()


def after_request(response):
    """
    Action to be taken after handling each incoming request.

    This function is executed after a view function has been called and a response is generated.

    Args:
        response (object): The response object generated by the view function.

    Returns:
        object: The response object with potential modifications.
    """
    # Determine if the current user is authenticated and get their user ID
    user_id = current_user.id if current_user.is_authenticated else None

    # Retrieve the timestamp stored in the "start_time" attribute of the Flask global object (g)
    timestamp = g.start_time

    # Save a request log entry to the database, including the endpoint, HTTP method, user ID, and timestamp
    save_request_log(request.endpoint, request.method, user_id, timestamp)

    # Return the response object
    return response
